# This image is used to patch Browsertrix's official image and solve some minor
# issues without waiting for a new release.
FROM webrecorder/browsertrix-crawler:1.12.0

WORKDIR /app
# See: https://github.com/webrecorder/browsertrix-crawler/pull/953
RUN yarn upgrade warcio
# Upgrade normalize-url to get some bugfixes. Hopefully soon to be upstreamed:
# https://github.com/webrecorder/browsertrix-crawler/pull/984
RUN yarn upgrade 'normalize-url@^=9.0.0'

WORKDIR /crawls
