# This image is used to patch Browsertrix's official image and solve some minor
# issues without waiting for a new release.
FROM webrecorder/browsertrix-crawler:1.13.2

WORKDIR /app

# Adjust any dependencies or modules in Browsertrix here in order to work
# around bugs or issues. For example:
# RUN yarn upgrade warcio

WORKDIR /crawls
